import {FormEvent,useEffect,useMemo,useState} from 'react'
import {useNavigate,useSearchParams} from 'react-router-dom'
import {api,json} from '../api'
import {DoctorOption,FilterOptions,queryString,VisitFilterOptions} from '../filters'

type Profile={metrics:{total_visits:number,most_recent_visit_date?:string,days_since_last_visit?:number,average_visit_interval?:number,pending_follow_ups:number},visits:{visit_date:string,purpose?:string,outcome?:string}[]}
export default function AddVisit(){
 const [params]=useSearchParams();const navigate=useNavigate()
 const [options,setOptions]=useState<FilterOptions>(),[visitOptions,setVisitOptions]=useState<VisitFilterOptions>({purposes:[],outcomes:[],products:[]})
 const [hq,setHq]=useState(''),[area,setArea]=useState(''),[doctorId,setDoctorId]=useState(params.get('doctor')||''),[doctorSearch,setDoctorSearch]=useState('')
 const [profile,setProfile]=useState<Profile>(),[selectedProducts,setSelectedProducts]=useState<number[]>([]),[followUp,setFollowUp]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 useEffect(()=>{api<VisitFilterOptions>('/visits/filter-options').then(setVisitOptions)},[])
 useEffect(()=>{api<FilterOptions>(`/doctors/filter-options?${queryString({hq,area:area||undefined,active:true})}`).then(next=>{setOptions(next);const requested=next.doctors.find(d=>String(d.id)===doctorId);if(doctorId&&!requested)setDoctorId('');else if(requested&&!area){setHq(requested.hq||'');setArea(requested.area||'')}})},[hq,area])
 useEffect(()=>{if(!doctorId){setProfile(undefined);return}api<Profile>(`/doctors/${doctorId}`).then(setProfile)},[doctorId])
 const doctors=useMemo(()=>area?(options?.doctors||[]).filter(d=>`${d.name} ${d.external_id||''} ${d.clinic_hospital||''}`.toLowerCase().includes(doctorSearch.toLowerCase())):[],[options,area,doctorSearch])
 const selectedDoctor=options?.doctors.find(d=>String(d.id)===doctorId)
 function toggleProduct(id:number){setSelectedProducts(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();setSaving(true);setError('');const form=new FormData(event.currentTarget)
  try{await api('/visits',json('POST',{doctor_id:Number(doctorId),visit_date:form.get('visit_date'),visit_time:form.get('visit_time')||null,purpose:form.get('purpose')||null,outcome:form.get('outcome')||null,notes:form.get('notes')||null,product_ids:selectedProducts,follow_up_required:followUp,follow_up_date:form.get('follow_up_date')||null,follow_up_reason:form.get('follow_up_reason')||null}));const action=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('data-action');if(action==='another'){event.currentTarget.reset();setDoctorId('');setProfile(undefined);setSelectedProducts([]);setFollowUp(false)}else navigate('/visits')}catch(e){setError((e as Error).message)}finally{setSaving(false)}
 }
 return <><div className="page-title"><div><h1>Record a visit</h1><p>Choose the territory first, then capture the call with doctor context.</p></div></div>{error&&<div className="error">{error}</div>}
 <form className="smart-visit" onSubmit={submit}><div className="panel visit-main"><div className="step-title"><span>1</span><div><b>Select doctor</b><small>HQ narrows areas; area narrows doctors.</small></div></div><div className="cascade-grid"><label>HQ<select value={hq} onChange={e=>{setHq(e.target.value);setArea('');setDoctorId('')}}><option value="">All HQs</option>{options?.hqs.map(x=><option key={x}>{x}</option>)}</select></label><label>Area<select required value={area} onChange={e=>{setArea(e.target.value);setDoctorId('')}}><option value="">Select area first</option>{options?.areas.map(x=><option key={x.id} value={x.name}>{x.name} ({x.doctor_count})</option>)}</select></label></div><label className="doctor-search">Find doctor<input value={doctorSearch} onChange={e=>setDoctorSearch(e.target.value)} disabled={!area} placeholder={area?'Type doctor name, ID or clinic':'Select an area first'}/></label><div className="doctor-picker">{area&&!doctors.length&&<p className="muted">No active doctors match this area and search.</p>}{doctors.slice(0,40).map(doctor=><button type="button" key={doctor.id} className={String(doctor.id)===doctorId?'chosen':''} onClick={()=>setDoctorId(String(doctor.id))}><b>{doctor.name}</b><span>{doctor.external_id||'No ID'} · {doctor.existing_specialty||'No specialty'}</span><small>{doctor.clinic_hospital||doctor.area}</small></button>)}</div>{selectedDoctor&&<div className="selected-doctor"><div><span>Selected doctor</span><b>{selectedDoctor.name}</b><small>{selectedDoctor.area} · {selectedDoctor.hq}</small></div>{profile&&<div className="doctor-signals"><span><b>{profile.metrics.total_visits}</b> total visits</span><span><b>{profile.metrics.days_since_last_visit??'—'}</b> days since last</span><span><b>{profile.metrics.pending_follow_ups}</b> pending follow-ups</span></div>}</div>}
 <div className="step-title"><span>2</span><div><b>Visit details</b><small>Only the date and doctor are required.</small></div></div><div className="cascade-grid"><label>Date<input name="visit_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Time<input name="visit_time" type="time" defaultValue={new Date().toTimeString().slice(0,5)}/></label><label>Purpose<input name="purpose" list="purposes" placeholder="Routine call, detailing…"/><datalist id="purposes">{visitOptions.purposes.map(x=><option key={x} value={x}/>)}</datalist></label><label>Outcome<input name="outcome" list="outcomes" placeholder="Positive, follow-up needed…"/><datalist id="outcomes">{visitOptions.outcomes.map(x=><option key={x} value={x}/>)}</datalist></label></div><label>Notes<textarea name="notes" rows={5} placeholder="Discussion, response, next action…"/></label></div>
 <aside className="visit-side"><div className="panel"><h2>Products discussed</h2><div className="product-picker">{visitOptions.products.map(product=><button type="button" key={product.id} className={selectedProducts.includes(product.id)?'selected':''} onClick={()=>toggleProduct(product.id)}>{product.name}<span>{selectedProducts.includes(product.id)?'✓':'+'}</span></button>)}</div>{!visitOptions.products.length&&<p className="muted">Add products from the Products page first.</p>}</div><div className="panel"><label className="switch"><input type="checkbox" checked={followUp} onChange={e=>setFollowUp(e.target.checked)}/><span/> Follow-up required</label>{followUp&&<div className="follow-fields"><label>Due date<input name="follow_up_date" type="date" required/></label><label>Reason<textarea name="follow_up_reason" rows={3} required/></label></div>}</div><div className="visit-actions"><button type="button" className="button" onClick={()=>navigate(-1)}>Cancel</button><button className="button" disabled={!doctorId||saving} data-action="another">Save & add another</button><button className="button primary" disabled={!doctorId||saving}>{saving?'Saving…':'Save visit'}</button></div></aside></form></>
}
