import {useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {api} from '../api'
import {FilterOptions,queryString} from '../filters'
type Area={id:number,name:string,doctors:number,active_doctors:number,visited_doctors:number,not_visited:number,visits:number,coverage_percentage:number,average_visits_per_doctor:number}
export default function Areas(){
 const today=new Date().toISOString().slice(0,10),first=today.slice(0,8)+'01';const [areas,setAreas]=useState<Area[]>([]),[options,setOptions]=useState<FilterOptions>(),[start,setStart]=useState(first),[end,setEnd]=useState(today),[hq,setHq]=useState(''),[sort,setSort]=useState('visits')
 useEffect(()=>{api<FilterOptions>('/doctors/filter-options?active=true').then(setOptions)},[])
 useEffect(()=>{api<Area[]>(`/areas?${queryString({start,end,hq})}`).then(setAreas)},[start,end,hq])
 const sorted=useMemo(()=>[...areas].sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):Number(b[sort as keyof Area])-Number(a[sort as keyof Area])),[areas,sort])
 const totals=useMemo(()=>({doctors:areas.reduce((n,x)=>n+x.active_doctors,0),visited:areas.reduce((n,x)=>n+x.visited_doctors,0),visits:areas.reduce((n,x)=>n+x.visits,0)}),[areas])
 return <><div className="page-title"><div><h1>Territory analysis</h1><p>Compare coverage and activity across areas.</p></div></div><div className="smart-filter"><div className="filter-grid"><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>HQ<select value={hq} onChange={e=>setHq(e.target.value)}><option value="">All HQs</option>{options?.hqs.map(x=><option key={x}>{x}</option>)}</select></label><label>Rank by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="visits">Most visits</option><option value="coverage_percentage">Highest coverage</option><option value="active_doctors">Doctor population</option><option value="name">Area name</option></select></label></div></div><div className="metrics territory-metrics"><div className="metric"><span>Active doctors</span><strong>{totals.doctors}</strong></div><div className="metric"><span>Doctors covered</span><strong>{totals.visited}</strong></div><div className="metric"><span>Total visits</span><strong>{totals.visits}</strong></div><div className="metric"><span>Overall coverage</span><strong>{totals.doctors?Math.round(totals.visited*1000/totals.doctors)/10:0}%</strong></div></div><div className="area-cards">{sorted.map((item,index)=><Link key={item.id} to={`/doctors?${queryString({area:item.name,hq,active:true})}`} className="area-card"><div className="area-rank">#{index+1}</div><div className="area-head"><div><h2>{item.name}</h2><span>{item.active_doctors} active doctors</span></div><strong>{item.coverage_percentage}%</strong></div><div className="coverage-line"><span style={{width:`${item.coverage_percentage}%`}}/></div><div className="area-stats"><span><b>{item.visits}</b> visits</span><span><b>{item.visited_doctors}</b> visited</span><span><b>{item.not_visited}</b> not visited</span><span><b>{item.average_visits_per_doctor}</b> avg/doctor</span></div></Link>)}</div>{!areas.length&&<div className="empty">No areas match this HQ and period.</div>}</>
}
