import {useEffect,useMemo,useState} from 'react'
import {api} from '../api'
import {FilterOptions,queryString} from '../filters'
type Visit={id:number,visit_date:string,visit_time?:string,purpose?:string,doctor:{name:string,area?:{name:string}},products:{name:string}[]}
export default function Calendar(){
 const now=new Date();const [month,setMonth]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`),[items,setItems]=useState<Visit[]>([]),[selected,setSelected]=useState(''),[options,setOptions]=useState<FilterOptions>(),[hq,setHq]=useState(''),[area,setArea]=useState(''),[doctor,setDoctor]=useState('')
 const [year,mon]=month.split('-').map(Number),start=`${month}-01`,end=new Date(year,mon,0).toISOString().slice(0,10)
 useEffect(()=>{api<FilterOptions>(`/doctors/filter-options?${queryString({hq,area})}`).then(setOptions)},[hq,area])
 useEffect(()=>{api<{items:Visit[]}>(`/visits?${queryString({date_from:start,date_to:end,hq,area,doctor_id:doctor,page_size:200})}`).then(x=>setItems(x.items))},[month,hq,area,doctor])
 const grouped=useMemo(()=>items.reduce<Record<string,Visit[]>>((all,visit)=>{(all[visit.visit_date]??=[]).push(visit);return all},{}),[items]),offset=new Date(year,mon-1,1).getDay(),days=new Date(year,mon,0).getDate(),chosen=selected?grouped[selected]||[]:[]
 return <><div className="page-title"><div><h1>Visit calendar</h1><p>See exactly where each working day was spent.</p></div></div><div className="smart-filter calendar-filter"><div className="filter-grid"><label>Month<input type="month" value={month} onChange={e=>{setMonth(e.target.value);setSelected('')}}/></label><label>HQ<select value={hq} onChange={e=>{setHq(e.target.value);setArea('');setDoctor('')}}><option value="">All HQs</option>{options?.hqs.map(x=><option key={x}>{x}</option>)}</select></label><label>Area<select value={area} onChange={e=>{setArea(e.target.value);setDoctor('')}}><option value="">All areas</option>{options?.areas.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label><label>Doctor<select value={doctor} onChange={e=>setDoctor(e.target.value)}><option value="">All doctors</option>{options?.doctors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div></div><div className="calendar"><div className="weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><b key={x}>{x}</b>)}</div><div className="days">{Array.from({length:offset},(_,i)=><span key={`x${i}`}/>)}{Array.from({length:days},(_,i)=>{const day=i+1,key=`${month}-${String(day).padStart(2,'0')}`,count=grouped[key]?.length||0;return <button key={key} className={selected===key?'selected':''} onClick={()=>setSelected(key)}><b>{day}</b>{count>0&&<em>{count} visit{count>1?'s':''}</em>}</button>})}</div></div>{selected&&<div className="panel day-detail"><h2>{selected} <small>{chosen.length} visits</small></h2>{!chosen.length?<p className="muted">No visits for this filter.</p>:chosen.map(visit=><div className="day-visit" key={visit.id}><b>{visit.visit_time?.slice(0,5)||'—'} · {visit.doctor.name}</b><span>{visit.doctor.area?.name||'No area'} · {visit.purpose||'No purpose recorded'}</span><small>{visit.products.map(product=>product.name).join(', ')}</small></div>)}</div>}</>
}
