import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {api} from '../api'
import {FilterOptions,queryString} from '../filters'
type Stats=Record<string,number>;type Trend={visit_date:string,visits:number,doctors:number}[];type AreaDatum={name:string,visits:number,coverage_percentage:number}
export default function Dashboard(){
 const today=new Date().toISOString().slice(0,10);const [start,setStart]=useState(today.slice(0,8)+'01'),[end,setEnd]=useState(today),[hq,setHq]=useState(''),[area,setArea]=useState(''),[options,setOptions]=useState<FilterOptions>(),[stats,setStats]=useState<Stats>(),[trend,setTrend]=useState<Trend>([]),[areas,setAreas]=useState<AreaDatum[]>([]),[error,setError]=useState('')
 useEffect(()=>{api<FilterOptions>(`/doctors/filter-options?${queryString({hq,active:true})}`).then(setOptions)},[hq])
 useEffect(()=>{const query=queryString({start,end,hq,area});Promise.all([api<Stats>(`/analytics/dashboard?${query}`),api<Trend>(`/analytics/trend?${query}`),api<AreaDatum[]>(`/areas?${query}`)]).then(([a,b,c])=>{setStats(a);setTrend(b);setAreas(c.sort((x,y)=>y.visits-x.visits).slice(0,8))}).catch(e=>setError(e.message))},[start,end,hq,area])
 if(error)return <div className="error">{error}</div>;if(!stats)return <div className="loading">Loading dashboard…</div>
 const visitsQuery=queryString({date_from:start,date_to:end,hq,area});const doctorQuery=queryString({hq,area,active:true});const areaData=areas
 const cards=[['Total doctors',stats.total_doctors,`/doctors?${doctorQuery}`],['Active doctors',stats.active_doctors,`/doctors?${doctorQuery}`],['Visits in period',stats.visits_in_period,`/visits?${visitsQuery}`],['Doctors covered',stats.visited_doctors_in_period,`/visits?${visitsQuery}`],['Coverage',`${stats.coverage_percentage}%`,`/reports?${queryString({start,end,hq,area})}`],['Areas covered',stats.areas_covered,'/areas'],['Upcoming follow-ups',stats.upcoming_follow_ups,'/follow-ups?due=upcoming'],['Overdue follow-ups',stats.overdue_follow_ups,'/follow-ups?due=overdue']]
 return <><div className="page-title"><div><h1>Dashboard</h1><p>Live activity with drill-down filters.</p></div></div><div className="dashboard-scope"><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>HQ<select value={hq} onChange={e=>{setHq(e.target.value);setArea('')}}><option value="">All HQs</option>{options?.hqs.map(x=><option key={x}>{x}</option>)}</select></label><label>Area<select value={area} onChange={e=>setArea(e.target.value)}><option value="">All areas</option>{options?.areas.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label></div><div className="metrics">{cards.map(([label,value,to])=><Link className="metric metric-link" key={label} to={String(to)}><span>{label}</span><strong>{value}</strong><small>View records →</small></Link>)}</div><div className="grid2"><div className="panel chart"><h2>Daily visit activity</h2>{trend.length?<ResponsiveContainer width="100%" height={230}><BarChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="visit_date" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="visits" fill="#248f6b" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<div className="empty">No visits in this selection.</div>}</div><div className="panel"><h2>Coverage for selection</h2><div className="coverage"><strong>{stats.coverage_percentage}%</strong><div><span style={{width:`${stats.coverage_percentage}%`}}/></div><p>{stats.visited_doctors_in_period} of {stats.active_doctors} active doctors visited</p></div></div></div><div className="panel chart area-chart"><h2>Area activity</h2>{areaData.length?<ResponsiveContainer width="100%" height={240}><BarChart data={areaData} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="name" type="category" width={100} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="visits" fill="#4bad88" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer>:<div className="empty">No territory activity in this selection.</div>}</div></>
}
