import {useEffect,useState} from 'react'
import {api} from '../api'
type Summary={doctors:number,active_doctors:number,visits:number,products:number,areas:number,imports:number,follow_ups:number}
type Visit={id:number,visit_date:string,doctor:{name:string},purpose?:string}
type Doctor={id:number,name:string,external_id?:string,active:boolean,area?:{name:string}}
type Product={id:number,name:string,visits:number}
type Area={id:number,name:string,doctors:number}
const purges=[
 ['visits','Visits','DELETE ALL VISITS','Deletes every visit, product link, and visit follow-up. Doctors and products remain.'],
 ['doctors','Doctors + visits','DELETE ALL DOCTORS AND VISITS','Deletes the complete doctor master and every visit. Products and import history remain.'],
 ['products','Products','DELETE ALL PRODUCTS','Deletes products and removes their links from visits. Visit records remain.'],
 ['follow_ups','Follow-ups','DELETE ALL FOLLOW UPS','Clears follow-up fields from visits without deleting visits.'],
 ['imports','Import history','DELETE IMPORT HISTORY','Deletes saved import previews and summaries. Doctors remain.'],
 ['areas','Area assignments','DELETE ALL AREAS','Removes all areas and unassigns doctors from them.'],
 ['everything','Everything','RESET EVERYTHING','Deletes doctors, visits, products, areas, and import history.'],
] as const
export default function DataManagement(){
 const [summary,setSummary]=useState<Summary>(),[visits,setVisits]=useState<Visit[]>([]),[doctors,setDoctors]=useState<Doctor[]>([]),[products,setProducts]=useState<Product[]>([]),[areas,setAreas]=useState<Area[]>([]),[search,setSearch]=useState(''),[reload,setReload]=useState(0),[message,setMessage]=useState('')
 useEffect(()=>{Promise.all([api<Summary>('/data-management/summary'),api<{items:Visit[]}>('/visits?page_size=20'),api<{items:Doctor[]}>('/doctors?page_size=20'),api<Product[]>('/products'),api<Area[]>('/areas')]).then(([s,v,d,p,a])=>{setSummary(s);setVisits(v.items);setDoctors(d.items);setProducts(p);setAreas(a)})},[reload])
 useEffect(()=>{const timer=setTimeout(()=>{if(search)Promise.all([api<{items:Visit[]}>(`/visits?page_size=20&q=${encodeURIComponent(search)}`),api<{items:Doctor[]}>(`/doctors?page_size=20&q=${encodeURIComponent(search)}`)]).then(([v,d])=>{setVisits(v.items);setDoctors(d.items)})},250);return()=>clearTimeout(timer)},[search])
 function finished(message:string){setMessage(message);setReload(x=>x+1)}
 async function removeVisit(item:Visit){if(!confirm(`Delete the ${item.visit_date} visit for ${item.doctor.name}?`))return;await api(`/visits/${item.id}`,{method:'DELETE'});finished('Visit deleted.')}
 async function removeDoctor(item:Doctor){if(!confirm(`Remove ${item.name}? Doctors with visits will be deactivated.`))return;const result=await api<{message:string}>(`/doctors/${item.id}`,{method:'DELETE'});finished(result.message||'Doctor removed.')}
 async function removeProduct(item:Product){if(!confirm(`Delete ${item.name}? It will be removed from ${item.visits} visit records.`))return;await api(`/data-management/products/${item.id}`,{method:'DELETE'});finished('Product deleted; visits were preserved.')}
 async function removeArea(item:Area){if(!confirm(`Delete area ${item.name}? ${item.doctors} doctors will become unassigned.`))return;await api(`/data-management/areas/${item.id}`,{method:'DELETE'});finished('Area deleted and affected doctors were unassigned.')}
 async function purge(category:string,phrase:string){const typed=prompt(`This is permanent. Type exactly:\n${phrase}`);if(typed!==phrase)return;await api(`/data-management/purge/${category}?confirm=${encodeURIComponent(typed)}`,{method:'DELETE'});finished(`${category} data cleared.`)}
 return <><div className="page-title"><div><h1>Data management</h1><p>Delete individual records or intentionally clear a complete data category.</p></div></div>{message&&<div className="success inline">{message}</div>}{summary&&<div className="data-summary">{Object.entries(summary).map(([key,value])=><div key={key}><span>{key.replaceAll('_',' ')}</span><b>{value}</b></div>)}</div>}<div className="smart-filter"><div className="filter-grid"><label className="search-field">Find a doctor or visit<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search before deleting a particular record"/></label></div></div><div className="data-grid"><div className="panel"><h2>Recent visits</h2><div className="manage-list">{visits.map(item=><div key={item.id}><span><b>{item.doctor.name}</b><small>{item.visit_date} · {item.purpose||'No purpose'}</small></span><button onClick={()=>removeVisit(item)}>Delete</button></div>)}</div></div><div className="panel"><h2>Doctors</h2><div className="manage-list">{doctors.map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.external_id||'No ID'} · {item.area?.name||'No area'} · {item.active?'Active':'Inactive'}</small></span><button onClick={()=>removeDoctor(item)}>Remove</button></div>)}</div></div><div className="panel"><h2>Products</h2><div className="manage-list">{products.map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.visits} linked visits</small></span><button onClick={()=>removeProduct(item)}>Delete</button></div>)}</div></div><div className="panel"><h2>Areas</h2><div className="manage-list">{areas.map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.doctors} assigned doctors</small></span><button onClick={()=>removeArea(item)}>Delete</button></div>)}</div></div></div><div className="purge-section"><h2>Clear a data category</h2><p>Each operation requires its own exact confirmation phrase.</p><div className="purge-grid">{purges.map(([category,label,phrase,description])=><div className={category==='everything'?'purge-card critical':'purge-card'} key={category}><span>{label}</span><p>{description}</p><code>{phrase}</code><button onClick={()=>purge(category,phrase)}>Clear {label.toLowerCase()}</button></div>)}</div></div></>
}
