import {FormEvent,useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {api,apiUrl,json} from '../api'
import {FilterOptions,queryString} from '../filters'

type Doctor={id:number,external_id?:string,name:string,mobile?:string,area?:{name:string},hq?:string,category?:string,specialty_group?:string,existing_specialty?:string,active:boolean,clinic_hospital?:string}
export default function Doctors(){
 const [url]=useSearchParams()
 const [data,setData]=useState<{items:Doctor[],total:number}>(),[options,setOptions]=useState<FilterOptions>(),[createOptions,setCreateOptions]=useState<FilterOptions>(),[q,setQ]=useState(url.get('q')||''),[debouncedQ,setDebouncedQ]=useState(url.get('q')||''),[page,setPage]=useState(1),[reload,setReload]=useState(0),[message,setMessage]=useState('')
 const [showAdd,setShowAdd]=useState(false),[savingDoctor,setSavingDoctor]=useState(false),[addError,setAddError]=useState('')
 const [hq,setHq]=useState(url.get('hq')||''),[area,setArea]=useState(url.get('area')||''),[category,setCategory]=useState(url.get('category')||''),[specialty,setSpecialty]=useState(url.get('specialty_group')||''),[status,setStatus]=useState(url.get('active')==='false'?'inactive':url.get('active')===null?'active':'active'),[sort,setSort]=useState('name')
 useEffect(()=>{const timer=setTimeout(()=>setDebouncedQ(q),250);return()=>clearTimeout(timer)},[q])
 useEffect(()=>{api<FilterOptions>(`/doctors/filter-options?${queryString({hq,active:status==='all'?undefined:status==='active'})}`).then(setOptions)},[hq,status,reload])
 useEffect(()=>{if(showAdd)api<FilterOptions>('/doctors/filter-options').then(setCreateOptions).catch(()=>setCreateOptions(undefined))},[showAdd])
 const query=useMemo(()=>queryString({q:debouncedQ,page,area,hq,category,specialty_group:specialty,active:status==='all'?undefined:status==='active',sort}),[debouncedQ,page,area,hq,category,specialty,status,sort])
 useEffect(()=>{api<{items:Doctor[],total:number}>(`/doctors?${query}`).then(setData)},[query,reload])
 function resetPage(){setPage(1)}
 function clear(){setQ('');setHq('');setArea('');setCategory('');setSpecialty('');setStatus('active');setSort('name');setPage(1)}
 async function remove(doctor:Doctor){if(!window.confirm(`Remove ${doctor.name}? Visit history will be preserved.`))return;const result=await api<{message:string}>(`/doctors/${doctor.id}`,{method:'DELETE'});setMessage(result.message);setReload(x=>x+1)}
 async function addDoctor(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;setSavingDoctor(true);setAddError('');setMessage('');const form=new FormData(formElement);const value=(key:string)=>String(form.get(key)||'').trim()||undefined;const payload={name:value('name'),existing_specialty:value('existing_specialty'),area:value('area'),hq:value('hq'),category:value('category'),mobile:value('mobile'),active:form.get('active')==='on',specialty_group:value('specialty_group'),doctor_status:value('doctor_status'),qualification:value('qualification'),gender:value('gender'),clinic_hospital:value('clinic_hospital')};try{const created=await api<Doctor>('/doctors',json('POST',payload));formElement.reset();setShowAdd(false);setMessage(`${created.name} added to the doctor master.`);setReload(x=>x+1)}catch(error){setAddError(error instanceof Error?error.message:'Could not add this doctor. Please try again.')}finally{setSavingDoctor(false)}}
 async function clearAll(){const confirmation=window.prompt('Type DELETE ALL DOCTORS to clear the master. Visit history will remain valid.');if(confirmation!=='DELETE ALL DOCTORS')return;const result=await api<{deleted:number,deactivated:number,message:string}>(`/doctors?confirm=${encodeURIComponent(confirmation)}`,{method:'DELETE'});setMessage(`${result.deleted} deleted and ${result.deactivated} deactivated.`);setReload(x=>x+1)}
 const chips=[['HQ',hq,()=>{setHq('');setArea('')}],['Area',area,()=>setArea('')],['Category',category,()=>setCategory('')],['Specialty',specialty,()=>setSpecialty('')],['Search',debouncedQ,()=>setQ('')]] as const
 const exportQuery=queryString({q:debouncedQ,area,hq,category,specialty_group:specialty,active:status==='all'?undefined:status==='active'})
 return <><div className="page-title"><div><h1>Doctors</h1><p>Search and segment the doctor master.</p></div><div className="actions"><a className="button" href={apiUrl(`/exports/doctors.csv?${exportQuery}`)}>Export filtered</a><button className="button" onClick={()=>{setShowAdd(value=>!value);setAddError('')}}>{showAdd?'Cancel':'Add doctor'}</button><Link className="button primary" to="/import">Import Excel</Link></div></div>{message&&<div className="success inline">{message}</div>}{showAdd&&<section className="panel manual-doctor-panel"><div className="section-heading"><div><h2>Add one doctor</h2><p className="muted">Enter the information you have. You can fill in more fields later.</p></div></div>{addError&&<div className="error">{addError}</div>}<form className="form" onSubmit={addDoctor}>
 <label>Doctor name *<input name="name" required maxLength={240} autoFocus placeholder="Dr. Full Name"/></label><label>Mobile<input name="mobile" type="tel" maxLength={40} placeholder="Phone number"/></label><label>Existing specialty / qualification<input name="existing_specialty" list="doctor-existing-specialties" maxLength={240}/><datalist id="doctor-existing-specialties">{createOptions?.existing_specialties?.map(value=><option key={value} value={value}/>)}</datalist></label><label>Area<input name="area" list="doctor-areas" maxLength={160} placeholder="Select or type a new area"/><datalist id="doctor-areas">{createOptions?.areas.map(value=><option key={value.id} value={value.name}/>)}</datalist></label><label>HQ<input name="hq" list="doctor-hqs" maxLength={160} placeholder="Select or type a new HQ"/><datalist id="doctor-hqs">{createOptions?.hqs.map(value=><option key={value} value={value}/>)}</datalist></label><label>Category<input name="category" list="doctor-categories" maxLength={120}/><datalist id="doctor-categories">{createOptions?.categories.map(value=><option key={value} value={value}/>)}</datalist></label><label>Specialty group<input name="specialty_group" list="doctor-specialty-groups" maxLength={160}/><datalist id="doctor-specialty-groups">{createOptions?.specialty_groups.map(value=><option key={value} value={value}/>)}</datalist></label><label>Qualification<input name="qualification" list="doctor-qualifications" maxLength={160}/><datalist id="doctor-qualifications">{createOptions?.qualifications.map(value=><option key={value} value={value}/>)}</datalist></label><label>Doctor status<input name="doctor_status" list="doctor-statuses" maxLength={120}/><datalist id="doctor-statuses">{createOptions?.doctor_statuses.map(value=><option key={value} value={value}/>)}</datalist></label><label>Gender<input name="gender" list="doctor-genders" maxLength={80} placeholder="Select or type"/><datalist id="doctor-genders">{[...new Set([...(createOptions?.genders||[]),'Female','Male','Other'])].map(value=><option key={value} value={value}/>)}</datalist></label><label className="wide">Clinic / hospital<input name="clinic_hospital" list="doctor-clinics" maxLength={240}/><datalist id="doctor-clinics">{createOptions?.clinics?.map(value=><option key={value} value={value}/>)}</datalist></label><label className="check"><input name="active" type="checkbox" defaultChecked/> Active doctor</label><div className="wide form-actions"><button className="button primary" disabled={savingDoctor}>{savingDoctor?'Saving…':'Save doctor'}</button></div></form></section>}
 <div className="smart-filter"><div className="filter-grid"><label className="search-field">Search<input placeholder="Name, ID, mobile, clinic…" value={q} onChange={e=>{setQ(e.target.value);resetPage()}}/></label><label>HQ<select value={hq} onChange={e=>{setHq(e.target.value);setArea('');resetPage()}}><option value="">All HQs</option>{options?.hqs.map(x=><option key={x}>{x}</option>)}</select></label><label>Area<select value={area} onChange={e=>{setArea(e.target.value);resetPage()}}><option value="">All areas</option>{options?.areas.map(x=><option key={x.id} value={x.name}>{x.name} ({x.doctor_count})</option>)}</select></label><label>Category<select value={category} onChange={e=>{setCategory(e.target.value);resetPage()}}><option value="">All categories</option>{options?.categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Specialty group<select value={specialty} onChange={e=>{setSpecialty(e.target.value);resetPage()}}><option value="">All specialties</option>{options?.specialty_groups.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);resetPage()}}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All</option></select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Doctor name</option><option value="area">Area</option><option value="hq">HQ</option><option value="category">Category</option></select></label></div><div className="filter-footer"><div className="active-filters">{chips.filter(([,value])=>value).map(([label,value,remove])=><button key={label} className="filter-chip" onClick={remove}>{label}: {value} ×</button>)}</div><button className="button" onClick={clear}>Reset filters</button></div></div>
 <div className="results-bar"><span><b>{data?.total??0}</b> doctors found</span><span>Page {page}</span></div><div className="table-wrap"><table><thead><tr><th>Doctor</th><th>Area / HQ</th><th>Specialty</th><th>Category</th><th>Status</th><th></th></tr></thead><tbody>{data?.items.map(doctor=><tr key={doctor.id}><td><Link to={`/doctors/${doctor.id}`}><b>{doctor.name}</b></Link><small>{doctor.external_id||doctor.clinic_hospital||doctor.mobile||'No ID/contact'}</small></td><td>{doctor.area?.name||'—'}<small>{doctor.hq}</small></td><td>{doctor.specialty_group||doctor.existing_specialty||'—'}<small>{doctor.existing_specialty}</small></td><td>{doctor.category||'—'}</td><td><span className={doctor.active?'pill active':'pill'}>{doctor.active?'Active':'Inactive'}</span></td><td><button className="icon-danger" onClick={()=>remove(doctor)}>Remove</button></td></tr>)}</tbody></table>{data?.items.length===0&&<div className="empty">No doctors match this combination. Clear a filter to broaden the list.</div>}</div><div className="pager"><button disabled={page===1} onClick={()=>setPage(x=>x-1)}>Previous</button><span>Showing {(page-1)*25+1}–{Math.min(page*25,data?.total||0)} of {data?.total||0}</span><button disabled={!data||page*25>=data.total} onClick={()=>setPage(x=>x+1)}>Next</button></div>
 <div className="danger-zone"><div><b>Clear doctor master</b><p>Unvisited doctors are deleted; visited doctors are safely deactivated.</p></div><button onClick={clearAll}>Clear all doctors</button></div></>
}
