import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {api} from '../api'
import {FilterOptions,queryString} from '../filters'
type FollowUp={id:number,doctor_id:number,doctor_name:string,area?:string,follow_up_date:string,reason?:string,status:string,visit_date:string}
export default function FollowUps(){
 const [url]=useSearchParams();const today=new Date().toISOString().slice(0,10);const [items,setItems]=useState<FollowUp[]>([]),[options,setOptions]=useState<FilterOptions>(),[reload,setReload]=useState(0),[status,setStatus]=useState(url.get('status')||'pending'),[due,setDue]=useState(url.get('due')||'all'),[hq,setHq]=useState(url.get('hq')||''),[area,setArea]=useState(url.get('area')||''),[doctor,setDoctor]=useState(url.get('doctor_id')||'')
 useEffect(()=>{api<FilterOptions>(`/doctors/filter-options?${queryString({hq,area,active:undefined})}`).then(setOptions)},[hq,area])
 const dates=useMemo(()=>{if(due==='overdue')return{due_to:new Date(Date.now()-86400000).toISOString().slice(0,10)};if(due==='today')return{due_from:today,due_to:today};if(due==='upcoming')return{due_from:new Date(Date.now()+86400000).toISOString().slice(0,10)};return{}},[due,today])
 const query=useMemo(()=>queryString({status,hq,area,doctor_id:doctor,...dates}),[status,hq,area,doctor,dates])
 useEffect(()=>{api<FollowUp[]>(`/follow-ups?${query}`).then(setItems)},[query,reload])
 async function complete(id:number){await api(`/follow-ups/${id}?status=completed`,{method:'PATCH'});setReload(x=>x+1)}
 return <><div className="page-title"><div><h1>Follow-ups</h1><p>Prioritize pending actions by due date and territory.</p></div></div><div className="smart-filter"><div className="preset-row"><span>Due</span>{[['all','All dates'],['overdue','Overdue'],['today','Today'],['upcoming','Upcoming']].map(([value,label])=><button className={due===value?'selected':''} key={value} onClick={()=>setDue(value)}>{label}</button>)}</div><div className="filter-grid"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="">Any status</option></select></label><label>HQ<select value={hq} onChange={e=>{setHq(e.target.value);setArea('');setDoctor('')}}><option value="">All HQs</option>{options?.hqs.map(x=><option key={x}>{x}</option>)}</select></label><label>Area<select value={area} onChange={e=>{setArea(e.target.value);setDoctor('')}}><option value="">All areas</option>{options?.areas.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label><label>Doctor<select value={doctor} onChange={e=>setDoctor(e.target.value)}><option value="">All doctors</option>{options?.doctors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><div className="filter-footer"><span className="results-count"><b>{items.length}</b> follow-ups</span><button className="button" onClick={()=>{setStatus('pending');setDue('all');setHq('');setArea('');setDoctor('')}}>Reset</button></div></div><div className="table-wrap"><table><thead><tr><th>Due</th><th>Doctor</th><th>Area</th><th>Reason</th><th>Source visit</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><span className={item.status==='pending'&&item.follow_up_date<today?'overdue':''}>{item.follow_up_date}</span><small>{item.status}</small></td><td><Link to={`/doctors/${item.doctor_id}`}><b>{item.doctor_name}</b></Link></td><td>{item.area||'—'}</td><td>{item.reason||'—'}</td><td>{item.visit_date}</td><td>{item.status==='pending'&&<button className="button" onClick={()=>complete(item.id)}>Mark complete</button>}</td></tr>)}</tbody></table>{!items.length&&<div className="empty">No follow-ups match these filters.</div>}</div></>
}
