import {FormEvent,useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {api,json} from '../api'
import {queryString} from '../filters'
type Product={id:number,name:string,description?:string,active:boolean,visits:number,doctors:number,areas:number}
export default function Products(){
 const [items,setItems]=useState<Product[]>([]),[error,setError]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState('visits');const load=()=>api<Product[]>('/products').then(setItems);useEffect(()=>{load()},[])
 async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await api('/products',json('POST',{name:form.get('name'),description:form.get('description')||null}));event.currentTarget.reset();load()}catch(e){setError((e as Error).message)}}
 const shown=useMemo(()=>items.filter(item=>item.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):Number(b[sort as keyof Product])-Number(a[sort as keyof Product])),[items,search,sort])
 return <><div className="page-title"><div><h1>Products</h1><p>Open any product to inspect the visits behind its numbers.</p></div></div>{error&&<div className="error">{error}</div>}<form className="toolbar product-add" onSubmit={add}><input name="name" required placeholder="Product name"/><input name="description" placeholder="Description (optional)"/><button className="button primary">Add product</button></form><div className="smart-filter product-filter"><div className="filter-grid"><label className="search-field">Find product<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product name"/></label><label>Rank by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="visits">Most visits</option><option value="doctors">Most doctors</option><option value="areas">Most areas</option><option value="name">Name</option></select></label></div></div><div className="product-cards">{shown.map(item=><Link key={item.id} to={`/visits?${queryString({product_id:item.id})}`} className="product-card"><div><h2>{item.name}</h2><p>{item.description||'No description'}</p></div><div className="product-stats"><span><b>{item.visits}</b> visits</span><span><b>{item.doctors}</b> doctors</span><span><b>{item.areas}</b> areas</span></div><small>View matching visits →</small></Link>)}</div>{!shown.length&&<div className="empty">No products match this search.</div>}</>
}
