import {useEffect,useState} from 'react'
import {Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {api} from '../api'
import {FilterOptions,queryString} from '../filters'
import {useSearchParams} from 'react-router-dom'
type Stats=Record<string,number>;type Coverage={active_doctors:number,visited:number,not_visited:number,coverage_percentage:number,frequency:Record<string,number>};type Area={name:string,visits:number,coverage_percentage:number};type Trend={visit_date:string,visits:number,doctors:number}
export default function Reports(){
 const [url]=useSearchParams();const today=new Date().toISOString().slice(0,10),first=today.slice(0,8)+'01'
 const [start,setStart]=useState(url.get('start')||first),[end,setEnd]=useState(url.get('end')||today),[hq,setHq]=useState(url.get('hq')||''),[area,setArea]=useState(url.get('area')||''),[category,setCategory]=useState(url.get('category')||''),[options,setOptions]=useState<FilterOptions>(),[stats,setStats]=useState<Stats>(),[coverage,setCoverage]=useState<Coverage>(),[areas,setAreas]=useState<Area[]>([]),[trend,setTrend]=useState<Trend[]>([]),[loading,setLoading]=useState(false)
 useEffect(()=>{api<FilterOptions>(`/doctors/filter-options?${queryString({hq,active:true})}`).then(setOptions)},[hq])
 function load(){setLoading(true);const query=queryString({start,end,hq,area,category});Promise.all([api<Stats>(`/analytics/dashboard?${query}`),api<Coverage>(`/analytics/coverage?${query}`),api<Trend[]>(`/analytics/trend?${query}`),api<Area[]>(`/areas?${query}`)]).then(([s,c,t,a])=>{setStats(s);setCoverage(c);setTrend(t);setAreas(a)}).finally(()=>setLoading(false))}
 useEffect(load,[])
 const exportQuery=queryString({date_from:start,date_to:end,hq,area})
 return <><div className="page-title"><div><h1>Activity report</h1><p>Build a territory-specific report from live visit records.</p></div><a className="button" href={`/api/exports/visits.csv?${exportQuery}`}>Export this report</a></div>
 <div className="smart-filter"><div className="filter-grid"><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>HQ<select value={hq} onChange={e=>{setHq(e.target.value);setArea('')}}><option value="">All HQs</option>{options?.hqs.map(x=><option key={x}>{x}</option>)}</select></label><label>Area<select value={area} onChange={e=>setArea(e.target.value)}><option value="">All areas</option>{options?.areas.map(x=><option key={x.id} value={x.name}>{x.name} ({x.doctor_count})</option>)}</select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{options?.categories.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="filter-footer"><span className="results-count">{hq||area||category?`Scoped to ${[hq,area,category].filter(Boolean).join(' · ')}`:'All territories'}</span><button className="button primary" onClick={load}>{loading?'Calculating…':'Run report'}</button></div></div>
 {stats&&coverage&&<><div className="metrics"><div className="metric"><span>Visits</span><strong>{stats.visits_in_period}</strong></div><div className="metric"><span>Doctors visited</span><strong>{stats.visited_doctors_in_period}</strong></div><div className="metric"><span>Active population</span><strong>{coverage.active_doctors}</strong></div><div className="metric"><span>Coverage</span><strong>{coverage.coverage_percentage}%</strong></div></div><div className="grid2 report-charts"><div className="panel"><h2>Activity over time</h2>{trend.length?<ResponsiveContainer width="100%" height={240}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="visit_date" tick={{fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Line dataKey="visits" stroke="#16815f" strokeWidth={3}/></LineChart></ResponsiveContainer>:<div className="empty">No activity in this period.</div>}</div><div className="panel"><h2>Visit frequency</h2><div className="frequency">{Object.entries(coverage.frequency).map(([key,value])=><div key={key}><span>{key.replaceAll('_',' ')}</span><b>{value}</b></div>)}</div></div></div><div className="panel report-area"><h2>Area comparison</h2>{areas.length?<ResponsiveContainer width="100%" height={260}><BarChart data={areas}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="visits" fill="#3fa77f" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>:<div className="empty">No area activity in this selection.</div>}</div></>}
 </>
}
