import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {api,apiUrl} from '../api'
import {FilterOptions,queryString,VisitFilterOptions} from '../filters'

type DoctorAnalysis={id:number,name:string,area?:string|null,hq?:string|null,category?:string|null,specialty?:string|null,active:boolean,visits:number,first_visit?:string|null,last_visit?:string|null,days_since_last_visit?:number|null,average_gap_days?:number|null,longest_gap_days?:number|null,products_discussed:number,pending_follow_ups:number}
type TerritoryAnalysis={name:string,doctors:number,active_doctors:number,visited_doctors:number,active_doctors_visited:number,not_visited:number,visits:number,coverage_percentage:number,average_visits_per_visited_doctor:number}
type Detail={period:{start:string,end:string,days:number},summary:{visits:number,doctors_in_scope:number,active_doctors:number,unique_doctors_visited:number,active_doctors_visited:number,not_visited_active_doctors:number,coverage_percentage:number,calls_per_calendar_day:number,calls_per_visited_doctor:number},frequency:Record<string,number>,doctors:DoctorAnalysis[],areas:TerritoryAnalysis[],hqs:TerritoryAnalysis[],products:{id:number,name:string,visits:number,doctors:number,areas:number}[],purposes:{name:string,visits:number}[],outcomes:{name:string,visits:number}[],trend:{date:string,visits:number,doctors:number}[],weekday_distribution:{name:string,visits:number}[],time_distribution:{name:string,visits:number}[],follow_ups:Record<string,number>}
type Granularity='day'|'week'|'month'

function groupTrend(rows:Detail['trend'],granularity:Granularity){
 const grouped=new Map<string,{period:string,visits:number,doctors:number}>()
 rows.forEach(row=>{
  let key=row.date
  if(granularity==='week'){
   const date=new Date(`${row.date}T00:00:00Z`);date.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7));key=date.toISOString().slice(0,10)
  }else if(granularity==='month')key=row.date.slice(0,7)
  const value=grouped.get(key)||{period:key,visits:0,doctors:0};value.visits+=row.visits;value.doctors+=row.doctors;grouped.set(key,value)
 })
 return [...grouped.values()]
}

export default function Reports(){
 const [url]=useSearchParams();const today=new Date().toISOString().slice(0,10),first=today.slice(0,8)+'01'
 const [start,setStart]=useState(url.get('start')||first),[end,setEnd]=useState(url.get('end')||today),[hq,setHq]=useState(url.get('hq')||''),[area,setArea]=useState(url.get('area')||''),[category,setCategory]=useState(url.get('category')||''),[doctor,setDoctor]=useState(url.get('doctor_id')||'')
 const [options,setOptions]=useState<FilterOptions>(),[visitOptions,setVisitOptions]=useState<VisitFilterOptions>({purposes:[],outcomes:[],products:[]}),[data,setData]=useState<Detail>(),[loading,setLoading]=useState(false),[error,setError]=useState(''),[granularity,setGranularity]=useState<Granularity>('day'),[doctorQuery,setDoctorQuery]=useState(''),[doctorPage,setDoctorPage]=useState(1),[product,setProduct]=useState(url.get('product_id')||''),[purpose,setPurpose]=useState(url.get('purpose')||''),[outcome,setOutcome]=useState(url.get('outcome')||''),[followUp,setFollowUp]=useState(url.get('follow_up_required')||'')
 useEffect(()=>{api<FilterOptions>(`/doctors/filter-options?${queryString({hq,area,category})}`).then(next=>{setOptions(next);if(doctor&&!next.doctors.some(item=>String(item.id)===doctor))setDoctor('')}).catch(()=>setOptions(undefined))},[hq,area,category])
 useEffect(()=>{api<VisitFilterOptions>('/visits/filter-options').then(setVisitOptions).catch(()=>setVisitOptions({purposes:[],outcomes:[],products:[]}))},[])
 async function load(){if(start&&end&&start>end){setError('Start date must be on or before end date.');return}setLoading(true);setError('');try{const result=await api<Detail>(`/analytics/call-analysis?${queryString({start,end,hq,area,category,doctor_id:doctor,product_id:product,purpose,outcome,follow_up_required:followUp===''?undefined:followUp==='true'})}`);setData(result);setDoctorPage(1)}catch(err){setError(err instanceof Error?err.message:'Could not load this report.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const exportQuery=queryString({date_from:start,date_to:end,hq,area,category,doctor_id:doctor,product_id:product,purpose,outcome,follow_up_required:followUp===''?undefined:followUp==='true'})
 const trend=useMemo(()=>data?groupTrend(data.trend,granularity):[],[data,granularity])
 const visibleDoctors=useMemo(()=>{const matching=(data?.doctors||[]).filter(row=>`${row.name} ${row.area||''} ${row.hq||''} ${row.specialty||''}`.toLowerCase().includes(doctorQuery.toLowerCase()));return matching.slice((doctorPage-1)*50,doctorPage*50)},[data,doctorQuery,doctorPage])
 const doctorMatches=(data?.doctors||[]).filter(row=>`${row.name} ${row.area||''} ${row.hq||''} ${row.specialty||''}`.toLowerCase().includes(doctorQuery.toLowerCase())).length
 const summary=data?.summary
 return <><div className="page-title"><div><h1>Detailed call analysis</h1><p>Doctor coverage, call patterns, products, outcomes, and follow-up performance.</p></div><div className="actions"><a className="button" href={apiUrl(`/exports/calls.csv?${exportQuery}`)}>Export call CSV</a><a className="button primary" href={apiUrl(`/exports/calls.xlsx?${exportQuery}`)}>Export Excel</a></div></div>
 <div className="smart-filter report-filter"><div className="filter-grid"><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>HQ<select value={hq} onChange={e=>{setHq(e.target.value);setArea('');setDoctor('')}}><option value="">All HQs</option>{options?.hqs.map(value=><option key={value}>{value}</option>)}</select></label><label>Area<select value={area} onChange={e=>{setArea(e.target.value);setDoctor('')}}><option value="">All areas</option>{options?.areas.map(value=><option key={value.id} value={value.name}>{value.name}</option>)}</select></label><label>Category<select value={category} onChange={e=>{setCategory(e.target.value);setArea('');setDoctor('')}}><option value="">All categories</option>{options?.categories.map(value=><option key={value}>{value}</option>)}</select></label><label>Doctor<select value={doctor} onChange={e=>setDoctor(e.target.value)}><option value="">All doctors</option>{options?.doctors.map(value=><option key={value.id} value={value.id}>{value.name}{value.area?` · ${value.area}`:''}</option>)}</select></label><label>Product discussed<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">All products</option>{visitOptions.products.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label>Call purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="">All purposes</option>{visitOptions.purposes.map(value=><option key={value}>{value}</option>)}</select></label><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">All outcomes</option>{visitOptions.outcomes.map(value=><option key={value}>{value}</option>)}</select></label><label>Follow-up<select value={followUp} onChange={e=>setFollowUp(e.target.value)}><option value="">Any</option><option value="true">Required</option><option value="false">Not required</option></select></label></div><div className="filter-footer"><span className="results-count">{data?`${data.period.start} to ${data.period.end} · ${data.period.days} calendar days`:'Run the report to calculate this scope'}</span><button className="button primary" onClick={load} disabled={loading}>{loading?'Analysing…':'Run detailed analysis'}</button></div></div>
 {error&&<div className="error">{error}</div>}{summary&&data&&<><div className="metrics report-metrics"><div className="metric"><span>Calls in period</span><strong>{summary.visits}</strong><small>{summary.calls_per_calendar_day} calls per calendar day</small></div><div className="metric"><span>Doctors visited</span><strong>{summary.unique_doctors_visited}</strong><small>{summary.active_doctors_visited} active doctors covered</small></div><div className="metric"><span>Active doctor coverage</span><strong>{summary.coverage_percentage}%</strong><small>{summary.not_visited_active_doctors} active doctors not visited</small></div><div className="metric"><span>Average calls per doctor</span><strong>{summary.calls_per_visited_doctor}</strong><small>Across doctors visited in this period</small></div><div className="metric"><span>Active population</span><strong>{summary.active_doctors}</strong><small>{summary.doctors_in_scope} total doctors in scope</small></div><div className="metric"><span>Follow-ups pending</span><strong>{data.follow_ups.pending}</strong><small>{data.follow_ups.overdue} overdue · {data.follow_ups.due_today} due today</small></div></div>
 <div className="grid2 report-charts"><div className="panel"><div className="analysis-panel-head"><h2>Call trend</h2><select aria-label="Trend grouping" value={granularity} onChange={e=>setGranularity(e.target.value as Granularity)}><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option></select></div>{trend.length?<ResponsiveContainer width="100%" height={270}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="period" tick={{fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Line name="Calls" dataKey="visits" stroke="#16815f" strokeWidth={3}/></LineChart></ResponsiveContainer>:<div className="empty">No calls in this period.</div>}</div><div className="panel"><h2>Active doctor call frequency</h2><div className="frequency">{Object.entries(data.frequency).map(([key,value])=><div key={key}><span>{key.replaceAll('_',' ')}</span><b>{value}</b></div>)}</div></div></div>
 <div className="grid2 report-charts"><div className="panel"><h2>Area call distribution</h2>{data.areas.length?<><ResponsiveContainer width="100%" height={245}><BarChart data={data.areas} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={100}/><Tooltip/><Bar name="Calls" dataKey="visits" fill="#318e6d" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer><div className="territory-detail"><b>Area · calls · active coverage</b>{data.areas.map(row=><span key={row.name}>{row.name}<strong>{row.visits} · {row.active_doctors_visited}/{row.active_doctors} ({row.coverage_percentage}%)</strong></span>)}</div></>:<div className="empty">No area data in this scope.</div>}</div><div className="panel"><h2>HQ call distribution</h2>{data.hqs.length?<><ResponsiveContainer width="100%" height={245}><BarChart data={data.hqs} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={100}/><Tooltip/><Bar name="Calls" dataKey="visits" fill="#6a9bd2" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer><div className="territory-detail"><b>HQ · calls · active coverage</b>{data.hqs.map(row=><span key={row.name}>{row.name}<strong>{row.visits} · {row.active_doctors_visited}/{row.active_doctors} ({row.coverage_percentage}%)</strong></span>)}</div></>:<div className="empty">No HQ data in this scope.</div>}</div></div>
 <div className="grid2 report-charts"><div className="panel"><h2>Call purpose</h2><div className="analysis-list">{data.purposes.map(row=><div key={row.name}><span>{row.name}</span><b>{row.visits}</b></div>)}{!data.purposes.length&&<p className="muted">No purpose data for these calls.</p>}</div></div><div className="panel"><h2>Call outcomes</h2><div className="analysis-list">{data.outcomes.map(row=><div key={row.name}><span>{row.name}</span><b>{row.visits}</b></div>)}{!data.outcomes.length&&<p className="muted">No outcome data for these calls.</p>}</div></div></div>
 <div className="grid2 report-charts"><div className="panel"><h2>Product activity</h2><div className="analysis-list">{data.products.map(row=><div key={row.id}><span>{row.name}<small>{row.doctors} unique doctors · {row.areas} areas</small></span><b>{row.visits}</b></div>)}{!data.products.length&&<p className="muted">No products were recorded in this period.</p>}</div></div><div className="panel"><h2>Follow-up status</h2><div className="analysis-list follow-up-analysis">{[['Required',data.follow_ups.required],['Pending',data.follow_ups.pending],['Overdue',data.follow_ups.overdue],['Due today',data.follow_ups.due_today],['Upcoming',data.follow_ups.upcoming],['Completed',data.follow_ups.completed],['Cancelled',data.follow_ups.cancelled]].map(([label,value])=><div key={String(label)}><span>{label}</span><b>{value}</b></div>)}</div></div></div>
 <div className="grid2 report-charts"><div className="panel"><h2>Calls by weekday</h2><div className="analysis-list">{data.weekday_distribution.map(row=><div key={row.name}><span>{row.name}</span><b>{row.visits}</b></div>)}</div></div><div className="panel"><h2>Calls by time of day</h2><div className="analysis-list">{data.time_distribution.map(row=><div key={row.name}><span>{row.name}</span><b>{row.visits}</b></div>)}</div></div></div>
 <div className="panel doctor-analysis"><div className="analysis-panel-head"><div><h2>Doctor call detail</h2><p className="muted">Includes zero-call doctors in the selected population. Gap values use calls inside this date range.</p></div><label>Find doctor<input value={doctorQuery} onChange={e=>{setDoctorQuery(e.target.value);setDoctorPage(1)}} placeholder="Name, area, HQ or specialty"/></label></div><div className="table-wrap"><table><thead><tr><th>Doctor</th><th>Territory</th><th>Calls</th><th>First call</th><th>Last call</th><th>Days since</th><th>Avg / longest gap</th><th>Products</th><th>Pending follow-ups</th></tr></thead><tbody>{visibleDoctors.map(row=><tr key={row.id}><td><Link to={`/doctors/${row.id}`}><b>{row.name}</b></Link><small>{row.specialty||'Specialty not recorded'} · {row.active?'Active':'Inactive'}</small></td><td>{row.area||'—'}<small>{row.hq||'No HQ'} · {row.category||'No category'}</small></td><td><b>{row.visits}</b></td><td>{row.first_visit||'—'}</td><td>{row.last_visit||'—'}</td><td>{row.days_since_last_visit??'—'}</td><td>{row.average_gap_days==null?'—':`${row.average_gap_days}d / ${row.longest_gap_days}d`}</td><td>{row.products_discussed}</td><td>{row.pending_follow_ups}</td></tr>)}</tbody></table>{!visibleDoctors.length&&<div className="empty">No doctors match this analysis.</div>}</div><div className="pager"><button disabled={doctorPage===1} onClick={()=>setDoctorPage(page=>page-1)}>Previous</button><span>Showing {doctorMatches?((doctorPage-1)*50+1):0}–{Math.min(doctorPage*50,doctorMatches)} of {doctorMatches}</span><button disabled={doctorPage*50>=doctorMatches} onClick={()=>setDoctorPage(page=>page+1)}>Next</button></div></div>
 </>}
 </>
}
