import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {api} from '../api'
import {FilterOptions,queryString,VisitFilterOptions} from '../filters'
type Visit={id:number,visit_date:string,visit_time?:string,purpose?:string,outcome?:string,notes?:string,doctor:{id:number,name:string,area?:{name:string},hq?:string},products:{id:number,name:string}[],follow_up_required:boolean,follow_up_date?:string}
const iso=(date:Date)=>date.toISOString().slice(0,10)
export default function Visits(){
 const [url]=useSearchParams()
 const [data,setData]=useState<{items:Visit[],total:number}>({items:[],total:0}),[options,setOptions]=useState<FilterOptions>(),[visitOptions,setVisitOptions]=useState<VisitFilterOptions>({purposes:[],outcomes:[],products:[]}),[page,setPage]=useState(1)
 const [q,setQ]=useState(url.get('q')||''),[dateFrom,setDateFrom]=useState(url.get('date_from')||''),[dateTo,setDateTo]=useState(url.get('date_to')||''),[hq,setHq]=useState(url.get('hq')||''),[area,setArea]=useState(url.get('area')||''),[doctor,setDoctor]=useState(url.get('doctor_id')||''),[product,setProduct]=useState(url.get('product_id')||''),[purpose,setPurpose]=useState(url.get('purpose')||''),[outcome,setOutcome]=useState(url.get('outcome')||''),[followUp,setFollowUp]=useState(url.get('follow_up_required')||'')
 useEffect(()=>{api<VisitFilterOptions>('/visits/filter-options').then(setVisitOptions)},[])
 useEffect(()=>{api<FilterOptions>(`/doctors/filter-options?${queryString({hq,area,active:undefined})}`).then(next=>{setOptions(next);if(doctor&&!next.doctors.some(d=>String(d.id)===doctor))setDoctor('')})},[hq,area])
 const query=useMemo(()=>queryString({q,date_from:dateFrom,date_to:dateTo,hq,area,doctor_id:doctor,product_id:product,purpose,outcome,follow_up_required:followUp,page,page_size:50}),[q,dateFrom,dateTo,hq,area,doctor,product,purpose,outcome,followUp,page])
 useEffect(()=>{const timer=setTimeout(()=>api<{items:Visit[],total:number}>(`/visits?${query}`).then(setData),180);return()=>clearTimeout(timer)},[query])
 function preset(kind:'today'|'week'|'month'|'clear'){const today=new Date();setDateTo(kind==='clear'?'':iso(today));if(kind==='today')setDateFrom(iso(today));if(kind==='week'){const start=new Date(today);start.setDate(today.getDate()-today.getDay()+1);setDateFrom(iso(start))}if(kind==='month')setDateFrom(`${iso(today).slice(0,8)}01`);if(kind==='clear')setDateFrom('');setPage(1)}
 function clear(){setQ('');setDateFrom('');setDateTo('');setHq('');setArea('');setDoctor('');setProduct('');setPurpose('');setOutcome('');setFollowUp('');setPage(1)}
 const exportQuery=queryString({date_from:dateFrom,date_to:dateTo,hq,area,doctor_id:doctor,product_id:product})
 return <><div className="page-title"><div><h1>Visit history</h1><p>Slice activity by territory, doctor, product, date, or outcome.</p></div><div className="actions"><a className="button" href={`/api/exports/visits.csv?${exportQuery}`}>Export filtered</a><Link className="button" to="/visits/bulk">+ Multiple visits</Link><Link className="button primary" to="/visits/new">+ Add visit</Link></div></div>
 <div className="smart-filter"><div className="preset-row"><span>Quick range</span><button onClick={()=>preset('today')}>Today</button><button onClick={()=>preset('week')}>This week</button><button onClick={()=>preset('month')}>This month</button><button onClick={()=>preset('clear')}>All time</button></div><div className="filter-grid"><label className="search-field">Search activity<input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Doctor, purpose, outcome, notes…"/></label><label>From<input type="date" value={dateFrom} onChange={e=>{setDateFrom(e.target.value);setPage(1)}}/></label><label>To<input type="date" value={dateTo} onChange={e=>{setDateTo(e.target.value);setPage(1)}}/></label><label>HQ<select value={hq} onChange={e=>{setHq(e.target.value);setArea('');setDoctor('');setPage(1)}}><option value="">All HQs</option>{options?.hqs.map(x=><option key={x}>{x}</option>)}</select></label><label>Area<select value={area} onChange={e=>{setArea(e.target.value);setDoctor('');setPage(1)}}><option value="">All areas</option>{options?.areas.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label><label>Doctor<select value={doctor} onChange={e=>{setDoctor(e.target.value);setPage(1)}}><option value="">All doctors</option>{options?.doctors.map(x=><option key={x.id} value={x.id}>{x.name} · {x.area}</option>)}</select></label><label>Product<select value={product} onChange={e=>{setProduct(e.target.value);setPage(1)}}><option value="">All products</option>{visitOptions.products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Purpose<select value={purpose} onChange={e=>{setPurpose(e.target.value);setPage(1)}}><option value="">All purposes</option>{visitOptions.purposes.map(x=><option key={x}>{x}</option>)}</select></label><label>Outcome<select value={outcome} onChange={e=>{setOutcome(e.target.value);setPage(1)}}><option value="">All outcomes</option>{visitOptions.outcomes.map(x=><option key={x}>{x}</option>)}</select></label><label>Follow-up<select value={followUp} onChange={e=>{setFollowUp(e.target.value);setPage(1)}}><option value="">Any</option><option value="true">Required</option><option value="false">Not required</option></select></label></div><div className="filter-footer"><span className="results-count"><b>{data.total}</b> visits match</span><button className="button" onClick={clear}>Reset filters</button></div></div>
 <div className="table-wrap"><table><thead><tr><th>Date / time</th><th>Doctor / territory</th><th>Purpose</th><th>Products</th><th>Outcome</th><th>Follow-up</th></tr></thead><tbody>{data.items.map(visit=><tr key={visit.id}><td><b>{visit.visit_date}</b><small>{visit.visit_time?.slice(0,5)||'Time not set'}</small></td><td><Link to={`/doctors/${visit.doctor.id}`}><b>{visit.doctor.name}</b></Link><small>{visit.doctor.area?.name||'No area'} · {visit.doctor.hq||'No HQ'}</small></td><td>{visit.purpose||'—'}<small>{visit.notes?.slice(0,70)}</small></td><td><div className="tag-list">{visit.products.map(item=><span key={item.id}>{item.name}</span>)}{!visit.products.length&&'—'}</div></td><td>{visit.outcome||'—'}</td><td>{visit.follow_up_required?<span className="pill new">{visit.follow_up_date||'Required'}</span>:'—'}</td></tr>)}</tbody></table>{!data.items.length&&<div className="empty">No visits match this filter set.</div>}</div><div className="pager"><button disabled={page===1} onClick={()=>setPage(x=>x-1)}>Previous</button><span>Page {page}</span><button disabled={page*50>=data.total} onClick={()=>setPage(x=>x+1)}>Next</button></div></>
}
